PROG=itest

SRCS= test.c vmm_instruction_emul.c

CFLAGS+= -D_VERIFICATION

.include <bsd.prog.mk>


Merge projects/bhyve to head nothing more.

'bhyve' was developed by grehan@ and Neel at NetApp (thanks!).

Special thanks to Peter Snyder, Joe Caradonna and Michael Dexter for their
support and encouragement.

There is no differnce between Revision 243703 and Revision 245652.
